// Auto-generated by regenerate.py — GP-adjusted, Finals-weighted, pooled sigma
// Finals games folded in: Knicks=1, Spurs=1
window.PROJECTIONS = {
  "nyk": [
    {
      "name": "Jalen Brunson",
      "pts": 28.0,
      "reb": 3.0,
      "ast": 4.9,
      "pra": 35.9,
      "sd_pts": 7.5,
      "sd_reb": 1.5,
      "sd_ast": 2.9,
      "gp": 15,
      "w": {
        "R1": 0.12,
        "R2": 0.18,
        "R3": 0.3,
        "F": 0.4
      }
    },
    {
      "name": "OG Anunoby",
      "pts": 17.8,
      "reb": 4.9,
      "ast": 1.5,
      "pra": 24.1,
      "sd_pts": 5.3,
      "sd_reb": 2.4,
      "sd_ast": 1.3,
      "gp": 13,
      "w": {
        "R1": 0.141,
        "R2": 0.106,
        "R3": 0.353,
        "F": 0.4
      }
    },
    {
      "name": "Karl-Anthony Towns",
      "pts": 17.0,
      "reb": 11.2,
      "ast": 4.9,
      "pra": 33.0,
      "sd_pts": 4.2,
      "sd_reb": 3.4,
      "sd_ast": 2.8,
      "gp": 15,
      "w": {
        "R1": 0.12,
        "R2": 0.18,
        "R3": 0.3,
        "F": 0.4
      }
    },
    {
      "name": "Mikal Bridges",
      "pts": 13.5,
      "reb": 3.3,
      "ast": 2.9,
      "pra": 19.7,
      "sd_pts": 6.8,
      "sd_reb": 1.6,
      "sd_ast": 1.6,
      "gp": 15,
      "w": {
        "R1": 0.12,
        "R2": 0.18,
        "R3": 0.3,
        "F": 0.4
      }
    },
    {
      "name": "Landry Shamet",
      "pts": 9.7,
      "reb": 1.0,
      "ast": 0.5,
      "pra": 11.2,
      "sd_pts": 6.2,
      "sd_reb": 1.2,
      "sd_ast": 1.0,
      "gp": 15,
      "w": {
        "R1": 0.12,
        "R2": 0.18,
        "R3": 0.3,
        "F": 0.4
      }
    },
    {
      "name": "Josh Hart",
      "pts": 8.6,
      "reb": 11.0,
      "ast": 5.3,
      "pra": 24.9,
      "sd_pts": 6.0,
      "sd_reb": 3.3,
      "sd_ast": 1.8,
      "gp": 15,
      "w": {
        "R1": 0.12,
        "R2": 0.18,
        "R3": 0.3,
        "F": 0.4
      }
    },
    {
      "name": "Miles McBride",
      "pts": 6.5,
      "reb": 1.4,
      "ast": 2.4,
      "pra": 10.2,
      "sd_pts": 6.6,
      "sd_reb": 1.4,
      "sd_ast": 1.2,
      "gp": 15,
      "w": {
        "R1": 0.12,
        "R2": 0.18,
        "R3": 0.3,
        "F": 0.4
      }
    },
    {
      "name": "Mitchell Robinson",
      "pts": 3.7,
      "reb": 5.7,
      "ast": 0.2,
      "pra": 9.6,
      "sd_pts": 3.1,
      "sd_reb": 2.0,
      "sd_ast": 0.5,
      "gp": 14,
      "w": {
        "R1": 0.13,
        "R2": 0.146,
        "R3": 0.324,
        "F": 0.4
      }
    }
  ],
  "sas": [
    {
      "name": "Victor Wembanyama",
      "pts": 24.6,
      "reb": 11.4,
      "ast": 2.5,
      "pra": 38.4,
      "sd_pts": 10.3,
      "sd_reb": 5.7,
      "sd_ast": 1.6,
      "gp": 18,
      "w": {
        "R1": 0.094,
        "R2": 0.212,
        "R3": 0.294,
        "F": 0.4
      }
    },
    {
      "name": "Stephon Castle",
      "pts": 18.2,
      "reb": 6.2,
      "ast": 5.3,
      "pra": 29.7,
      "sd_pts": 5.7,
      "sd_reb": 2.3,
      "sd_ast": 2.3,
      "gp": 19,
      "w": {
        "R1": 0.113,
        "R2": 0.204,
        "R3": 0.283,
        "F": 0.4
      }
    },
    {
      "name": "Dylan Harper",
      "pts": 14.2,
      "reb": 6.5,
      "ast": 2.0,
      "pra": 22.8,
      "sd_pts": 6.9,
      "sd_reb": 3.0,
      "sd_ast": 1.4,
      "gp": 19,
      "w": {
        "R1": 0.113,
        "R2": 0.204,
        "R3": 0.283,
        "F": 0.4
      }
    },
    {
      "name": "Julian Champagnie",
      "pts": 13.3,
      "reb": 7.5,
      "ast": 1.3,
      "pra": 22.1,
      "sd_pts": 5.5,
      "sd_reb": 2.4,
      "sd_ast": 1.0,
      "gp": 19,
      "w": {
        "R1": 0.113,
        "R2": 0.204,
        "R3": 0.283,
        "F": 0.4
      }
    },
    {
      "name": "De'Aaron Fox",
      "pts": 12.2,
      "reb": 4.0,
      "ast": 5.5,
      "pra": 21.8,
      "sd_pts": 6.0,
      "sd_reb": 2.4,
      "sd_ast": 2.0,
      "gp": 17,
      "w": {
        "R1": 0.131,
        "R2": 0.236,
        "R3": 0.234,
        "F": 0.4
      }
    },
    {
      "name": "Devin Vassell",
      "pts": 11.5,
      "reb": 6.5,
      "ast": 2.8,
      "pra": 20.7,
      "sd_pts": 3.7,
      "sd_reb": 2.7,
      "sd_ast": 0.8,
      "gp": 19,
      "w": {
        "R1": 0.113,
        "R2": 0.204,
        "R3": 0.283,
        "F": 0.4
      }
    },
    {
      "name": "Keldon Johnson",
      "pts": 6.6,
      "reb": 2.0,
      "ast": 0.5,
      "pra": 9.1,
      "sd_pts": 4.9,
      "sd_reb": 2.5,
      "sd_ast": 0.8,
      "gp": 19,
      "w": {
        "R1": 0.113,
        "R2": 0.204,
        "R3": 0.283,
        "F": 0.4
      }
    },
    {
      "name": "Luke Kornet",
      "pts": 2.4,
      "reb": 2.8,
      "ast": 0.4,
      "pra": 5.7,
      "sd_pts": 3.9,
      "sd_reb": 3.1,
      "sd_ast": 0.9,
      "gp": 19,
      "w": {
        "R1": 0.113,
        "R2": 0.204,
        "R3": 0.283,
        "F": 0.4
      }
    }
  ]
};
