// Auto-generated by regenerate.py — GP-adjusted, Finals-weighted, pooled sigma
// Finals games folded in: Knicks=3, Spurs=3
window.PROJECTIONS = {
  "nyk": [
    {
      "name": "Jalen Brunson",
      "pts": 27.1,
      "reb": 3.8,
      "ast": 5.2,
      "pra": 36.2,
      "sd_pts": 7.3,
      "sd_reb": 1.6,
      "sd_ast": 2.8,
      "gp": 17,
      "w": {
        "R1": 0.07,
        "R2": 0.105,
        "R3": 0.175,
        "F": 0.65
      }
    },
    {
      "name": "OG Anunoby",
      "pts": 19.8,
      "reb": 4.7,
      "ast": 1.7,
      "pra": 26.3,
      "sd_pts": 5.4,
      "sd_reb": 2.4,
      "sd_ast": 1.3,
      "gp": 15,
      "w": {
        "R1": 0.082,
        "R2": 0.062,
        "R3": 0.206,
        "F": 0.65
      }
    },
    {
      "name": "Karl-Anthony Towns",
      "pts": 16.5,
      "reb": 10.9,
      "ast": 3.9,
      "pra": 31.3,
      "sd_pts": 4.3,
      "sd_reb": 3.3,
      "sd_ast": 2.9,
      "gp": 17,
      "w": {
        "R1": 0.07,
        "R2": 0.105,
        "R3": 0.175,
        "F": 0.65
      }
    },
    {
      "name": "Mikal Bridges",
      "pts": 12.5,
      "reb": 4.3,
      "ast": 3.3,
      "pra": 20.1,
      "sd_pts": 7.2,
      "sd_reb": 1.7,
      "sd_ast": 1.8,
      "gp": 17,
      "w": {
        "R1": 0.07,
        "R2": 0.105,
        "R3": 0.175,
        "F": 0.65
      }
    },
    {
      "name": "Landry Shamet",
      "pts": 8.9,
      "reb": 1.9,
      "ast": 1.2,
      "pra": 11.9,
      "sd_pts": 6.1,
      "sd_reb": 1.4,
      "sd_ast": 1.0,
      "gp": 17,
      "w": {
        "R1": 0.07,
        "R2": 0.105,
        "R3": 0.175,
        "F": 0.65
      }
    },
    {
      "name": "Josh Hart",
      "pts": 8.4,
      "reb": 9.4,
      "ast": 4.9,
      "pra": 22.8,
      "sd_pts": 6.4,
      "sd_reb": 3.2,
      "sd_ast": 1.7,
      "gp": 17,
      "w": {
        "R1": 0.07,
        "R2": 0.105,
        "R3": 0.175,
        "F": 0.65
      }
    },
    {
      "name": "Miles McBride",
      "pts": 4.8,
      "reb": 1.2,
      "ast": 1.8,
      "pra": 7.7,
      "sd_pts": 6.4,
      "sd_reb": 1.3,
      "sd_ast": 1.2,
      "gp": 17,
      "w": {
        "R1": 0.07,
        "R2": 0.105,
        "R3": 0.175,
        "F": 0.65
      }
    },
    {
      "name": "Mitchell Robinson",
      "pts": 4.7,
      "reb": 4.8,
      "ast": 0.1,
      "pra": 9.6,
      "sd_pts": 2.9,
      "sd_reb": 2.0,
      "sd_ast": 0.4,
      "gp": 16,
      "w": {
        "R1": 0.076,
        "R2": 0.085,
        "R3": 0.189,
        "F": 0.65
      }
    }
  ],
  "sas": [
    {
      "name": "Victor Wembanyama",
      "pts": 27.1,
      "reb": 10.1,
      "ast": 3.1,
      "pra": 40.4,
      "sd_pts": 10.0,
      "sd_reb": 5.5,
      "sd_ast": 1.7,
      "gp": 20,
      "w": {
        "R1": 0.055,
        "R2": 0.124,
        "R3": 0.172,
        "F": 0.65
      }
    },
    {
      "name": "Stephon Castle",
      "pts": 18.4,
      "reb": 5.4,
      "ast": 5.0,
      "pra": 28.8,
      "sd_pts": 5.6,
      "sd_reb": 2.2,
      "sd_ast": 2.3,
      "gp": 21,
      "w": {
        "R1": 0.066,
        "R2": 0.119,
        "R3": 0.165,
        "F": 0.65
      }
    },
    {
      "name": "Dylan Harper",
      "pts": 14.1,
      "reb": 6.9,
      "ast": 2.7,
      "pra": 23.7,
      "sd_pts": 6.6,
      "sd_reb": 2.9,
      "sd_ast": 1.4,
      "gp": 21,
      "w": {
        "R1": 0.066,
        "R2": 0.119,
        "R3": 0.165,
        "F": 0.65
      }
    },
    {
      "name": "De'Aaron Fox",
      "pts": 13.9,
      "reb": 3.6,
      "ast": 6.0,
      "pra": 23.5,
      "sd_pts": 5.8,
      "sd_reb": 2.3,
      "sd_ast": 1.9,
      "gp": 19,
      "w": {
        "R1": 0.076,
        "R2": 0.137,
        "R3": 0.136,
        "F": 0.65
      }
    },
    {
      "name": "Devin Vassell",
      "pts": 12.0,
      "reb": 6.4,
      "ast": 2.7,
      "pra": 21.1,
      "sd_pts": 3.5,
      "sd_reb": 2.8,
      "sd_ast": 1.1,
      "gp": 21,
      "w": {
        "R1": 0.066,
        "R2": 0.119,
        "R3": 0.165,
        "F": 0.65
      }
    },
    {
      "name": "Julian Champagnie",
      "pts": 11.8,
      "reb": 5.3,
      "ast": 1.6,
      "pra": 18.7,
      "sd_pts": 5.3,
      "sd_reb": 2.5,
      "sd_ast": 1.0,
      "gp": 21,
      "w": {
        "R1": 0.066,
        "R2": 0.119,
        "R3": 0.165,
        "F": 0.65
      }
    },
    {
      "name": "Keldon Johnson",
      "pts": 6.0,
      "reb": 2.4,
      "ast": 0.7,
      "pra": 9.1,
      "sd_pts": 4.8,
      "sd_reb": 2.4,
      "sd_ast": 0.8,
      "gp": 21,
      "w": {
        "R1": 0.066,
        "R2": 0.119,
        "R3": 0.165,
        "F": 0.65
      }
    },
    {
      "name": "Luke Kornet",
      "pts": 2.1,
      "reb": 3.4,
      "ast": 0.7,
      "pra": 6.1,
      "sd_pts": 3.8,
      "sd_reb": 3.0,
      "sd_ast": 0.9,
      "gp": 21,
      "w": {
        "R1": 0.066,
        "R2": 0.119,
        "R3": 0.165,
        "F": 0.65
      }
    }
  ]
};
