// Auto-generated by regenerate.py — GP-adjusted, Finals-weighted, pooled sigma
// Finals games folded in: Knicks=2, Spurs=2
window.PROJECTIONS = {
  "nyk": [
    {
      "name": "Jalen Brunson",
      "pts": 25.8,
      "reb": 3.5,
      "ast": 5.3,
      "pra": 34.6,
      "sd_pts": 7.5,
      "sd_reb": 1.6,
      "sd_ast": 2.8,
      "gp": 16,
      "w": {
        "R1": 0.09,
        "R2": 0.135,
        "R3": 0.225,
        "F": 0.55
      }
    },
    {
      "name": "Karl-Anthony Towns",
      "pts": 18.0,
      "reb": 11.7,
      "ast": 4.7,
      "pra": 34.4,
      "sd_pts": 4.2,
      "sd_reb": 3.4,
      "sd_ast": 2.8,
      "gp": 16,
      "w": {
        "R1": 0.09,
        "R2": 0.135,
        "R3": 0.225,
        "F": 0.55
      }
    },
    {
      "name": "OG Anunoby",
      "pts": 17.6,
      "reb": 4.7,
      "ast": 1.9,
      "pra": 24.2,
      "sd_pts": 5.1,
      "sd_reb": 2.4,
      "sd_ast": 1.3,
      "gp": 14,
      "w": {
        "R1": 0.106,
        "R2": 0.079,
        "R3": 0.265,
        "F": 0.55
      }
    },
    {
      "name": "Mikal Bridges",
      "pts": 15.4,
      "reb": 4.1,
      "ast": 3.7,
      "pra": 23.2,
      "sd_pts": 6.7,
      "sd_reb": 1.7,
      "sd_ast": 1.8,
      "gp": 16,
      "w": {
        "R1": 0.09,
        "R2": 0.135,
        "R3": 0.225,
        "F": 0.55
      }
    },
    {
      "name": "Landry Shamet",
      "pts": 10.5,
      "reb": 1.3,
      "ast": 0.9,
      "pra": 12.7,
      "sd_pts": 6.3,
      "sd_reb": 1.2,
      "sd_ast": 1.0,
      "gp": 16,
      "w": {
        "R1": 0.09,
        "R2": 0.135,
        "R3": 0.225,
        "F": 0.55
      }
    },
    {
      "name": "Josh Hart",
      "pts": 6.4,
      "reb": 9.5,
      "ast": 4.9,
      "pra": 20.8,
      "sd_pts": 6.4,
      "sd_reb": 3.3,
      "sd_ast": 1.7,
      "gp": 16,
      "w": {
        "R1": 0.09,
        "R2": 0.135,
        "R3": 0.225,
        "F": 0.55
      }
    },
    {
      "name": "Miles McBride",
      "pts": 6.1,
      "reb": 1.5,
      "ast": 2.2,
      "pra": 9.9,
      "sd_pts": 6.4,
      "sd_reb": 1.3,
      "sd_ast": 1.1,
      "gp": 16,
      "w": {
        "R1": 0.09,
        "R2": 0.135,
        "R3": 0.225,
        "F": 0.55
      }
    },
    {
      "name": "Mitchell Robinson",
      "pts": 4.7,
      "reb": 5.0,
      "ast": 0.1,
      "pra": 9.8,
      "sd_pts": 3.0,
      "sd_reb": 2.0,
      "sd_ast": 0.5,
      "gp": 15,
      "w": {
        "R1": 0.097,
        "R2": 0.109,
        "R3": 0.243,
        "F": 0.55
      }
    }
  ],
  "sas": [
    {
      "name": "Victor Wembanyama",
      "pts": 25.8,
      "reb": 10.7,
      "ast": 2.4,
      "pra": 38.8,
      "sd_pts": 10.1,
      "sd_reb": 5.6,
      "sd_ast": 1.6,
      "gp": 19,
      "w": {
        "R1": 0.071,
        "R2": 0.159,
        "R3": 0.221,
        "F": 0.55
      }
    },
    {
      "name": "Stephon Castle",
      "pts": 17.1,
      "reb": 5.6,
      "ast": 5.0,
      "pra": 27.6,
      "sd_pts": 5.7,
      "sd_reb": 2.2,
      "sd_ast": 2.3,
      "gp": 20,
      "w": {
        "R1": 0.085,
        "R2": 0.153,
        "R3": 0.212,
        "F": 0.55
      }
    },
    {
      "name": "De'Aaron Fox",
      "pts": 14.5,
      "reb": 3.8,
      "ast": 5.4,
      "pra": 23.6,
      "sd_pts": 5.9,
      "sd_reb": 2.3,
      "sd_ast": 1.9,
      "gp": 18,
      "w": {
        "R1": 0.098,
        "R2": 0.177,
        "R3": 0.175,
        "F": 0.55
      }
    },
    {
      "name": "Dylan Harper",
      "pts": 14.4,
      "reb": 6.3,
      "ast": 2.3,
      "pra": 23.0,
      "sd_pts": 6.7,
      "sd_reb": 2.9,
      "sd_ast": 1.4,
      "gp": 20,
      "w": {
        "R1": 0.085,
        "R2": 0.153,
        "R3": 0.212,
        "F": 0.55
      }
    },
    {
      "name": "Devin Vassell",
      "pts": 12.2,
      "reb": 7.1,
      "ast": 3.4,
      "pra": 22.7,
      "sd_pts": 3.6,
      "sd_reb": 2.8,
      "sd_ast": 1.0,
      "gp": 20,
      "w": {
        "R1": 0.085,
        "R2": 0.153,
        "R3": 0.212,
        "F": 0.55
      }
    },
    {
      "name": "Julian Champagnie",
      "pts": 11.7,
      "reb": 6.5,
      "ast": 1.2,
      "pra": 19.5,
      "sd_pts": 5.4,
      "sd_reb": 2.4,
      "sd_ast": 1.0,
      "gp": 20,
      "w": {
        "R1": 0.085,
        "R2": 0.153,
        "R3": 0.212,
        "F": 0.55
      }
    },
    {
      "name": "Keldon Johnson",
      "pts": 5.7,
      "reb": 2.6,
      "ast": 0.9,
      "pra": 9.2,
      "sd_pts": 4.9,
      "sd_reb": 2.4,
      "sd_ast": 0.8,
      "gp": 20,
      "w": {
        "R1": 0.085,
        "R2": 0.153,
        "R3": 0.212,
        "F": 0.55
      }
    },
    {
      "name": "Luke Kornet",
      "pts": 2.1,
      "reb": 2.9,
      "ast": 0.3,
      "pra": 5.3,
      "sd_pts": 3.8,
      "sd_reb": 3.0,
      "sd_ast": 0.9,
      "gp": 20,
      "w": {
        "R1": 0.085,
        "R2": 0.153,
        "R3": 0.212,
        "F": 0.55
      }
    }
  ]
};
