#!/usr/bin/env python3
"""Rebuild projections.js from the Excel game logs.
GP-adjusted weighting, pure form, pooled sigma.
Tiers: R1/R2/R3 plus an optional FINALS tier that is the HEAVIEST and
grows as Finals games accrue. Add a 'Knicks F' / 'Spurs F' sheet (same
columns) once Finals games are played and they auto-fold in."""
import pandas as pd, numpy as np, json, sys

XLSX = "NBA_Finals_Spurs_Knicks_Stats.xlsx"

# Base playoff tiers (used when no Finals games yet). Sum to 1.
BASE_PLAYOFF = {"R1":0.20,"R2":0.30,"R3":0.50}
# Series lengths for GP-fraction (Finals length grows with games played).
SERIES_LEN = {"R1_NYK":6,"R2_NYK":4,"R3_NYK":4,
              "R1_SAS":5,"R2_SAS":5,"R3_SAS":7}

# Finals tier weight as a function of Finals games played (heaviest tier).
def finals_weight(n_finals):
    if n_finals<=0: return 0.0
    if n_finals==1: return 0.40
    if n_finals==2: return 0.55
    return 0.65   # 3+ games: series dominates

ROUND_SHEETS = {  # team -> list of (sheet_round_label, tierkey)
 "Knicks":[("R1","R1"),("R2","R2"),("R3","R3"),("F","F")],
 "Spurs": [("R1","R1"),("R2","R2"),("R3","R3"),("F","F")],
}

def parse_ma(s):
    if isinstance(s,str) and "-" in s:
        a,b=s.split("-"); 
        try: return int(a),int(b)
        except: return 0,0
    return 0,0

def load_sheet(xls, name):
    if name not in xls.sheet_names: return None
    raw=pd.read_excel(xls,sheet_name=name,header=None)
    games=[]; cur=[]
    for _,row in raw.iterrows():
        v=list(row.values)
        if v[0]=="Player" or (len(v)>1 and isinstance(v[1],str) and v[1]=="MIN"):
            if cur: games.append(cur); cur=[]
            continue
        if pd.isna(v[0]): continue
        cur.append(v)
    if cur: games.append(cur)
    recs=[]
    for gi,g in enumerate(games):
        for r in g:
            if str(r[1])=="DNP": continue
            recs.append({"game":gi,"Player":r[0],
                "FGM":parse_ma(r[3])[0],"TPM":parse_ma(r[4])[0],"FTM":parse_ma(r[5])[0],
                "REB":float(r[6]),"AST":float(r[7])})
    return pd.DataFrame(recs) if recs else None

def main():
    xls=pd.ExcelFile(XLSX)
    out={"nyk":[], "sas":[]}
    meta={}
    for team,sheets in ROUND_SHEETS.items():
        frames={}
        for rd,tier in sheets:
            f=load_sheet(xls,f"{team} {rd}")
            if f is not None: frames[tier]=f
        n_finals = frames["F"]["game"].nunique() if "F" in frames else 0
        players=sorted(set().union(*[set(f.Player) for f in frames.values()]))
        rows=[]
        for p in players:
            rmeans={}; gp={}; allp=[]; allr=[]; alla=[]
            for tier,f in frames.items():
                pf=f[f.Player==p]
                if len(pf)==0: continue
                pts=2*pf.FGM+pf.TPM+pf.FTM
                rmeans[tier]={"PTS":pts.mean(),"REB":pf.REB.mean(),"AST":pf.AST.mean()}
                gp[tier]=pf["game"].nunique()
                allp+=list(pts); allr+=list(pf.REB); alla+=list(pf.AST)
            # ----- build tier weights -----
            fw=finals_weight(n_finals if "F" in gp else 0)
            playoff_budget=1.0-fw
            raw={}
            for tier in ["R1","R2","R3"]:
                if tier in gp:
                    slen=SERIES_LEN.get(f"{tier}_{'NYK' if team=='Knicks' else 'SAS'}",
                                        max(gp[tier],1))
                    raw[tier]=BASE_PLAYOFF[tier]*(gp[tier]/slen)
            ptot=sum(raw.values()) or 1
            w={t:(raw[t]/ptot)*playoff_budget for t in raw}
            if "F" in gp and fw>0: w["F"]=fw
            wtot=sum(w.values()) or 1
            w={t:w[t]/wtot for t in w}
            proj={s:sum(w[t]*rmeans[t][s] for t in w) for s in ["PTS","REB","AST"]}
            sd={"PTS":np.std(allp,ddof=1) if len(allp)>1 else 0.0,
                "REB":np.std(allr,ddof=1) if len(allr)>1 else 0.0,
                "AST":np.std(alla,ddof=1) if len(alla)>1 else 0.0}
            name="Julian Champagnie" if p=="Julian Chamagnie" else p
            rows.append({"name":name,
                "pts":round(proj["PTS"],1),"reb":round(proj["REB"],1),"ast":round(proj["AST"],1),
                "pra":round(sum(proj.values()),1),
                "sd_pts":round(sd["PTS"],1),"sd_reb":round(sd["REB"],1),"sd_ast":round(sd["AST"],1),
                "gp":sum(gp.values()),"w":{t:round(v,3) for t,v in w.items()}})
        rows.sort(key=lambda x:-x["pts"])
        out["nyk" if team=="Knicks" else "sas"]=rows
        meta[team]=n_finals
    open("projections.js","w").write(
        "// Auto-generated by regenerate.py — GP-adjusted, Finals-weighted, pooled sigma\n"
        f"// Finals games folded in: Knicks={meta.get('Knicks',0)}, Spurs={meta.get('Spurs',0)}\n"
        "window.PROJECTIONS = "+json.dumps(out,indent=2)+";\n")
    print(f"projections.js rebuilt. Finals games: {meta}")

if __name__=="__main__":
    main()
